### ISSUE TITLE
Wanted to join your team in HackSquad.

### ISSUE THREAD

**Issue by alpha2207** [btrezzy/btrezzy#1]
Sorry I am commenting here but I want to join your team in hacksquad and I didn't get any of your social other than this so I am commenting here. Please let me know if I can join your team.

**Comment by btrezzy** [comment]
You are welcomed!
https://www.hacksquad.dev/friend/bmlyYWprdW1hcnBhdGVsMjFAZ21haWwuY29t

**Comment by btrezzy** [comment]
You are welcomed!
https://www.hacksquad.dev/friend/bmlyYWprdW1hcnBhdGVsMjFAZ21haWwuY29t
